---
# Introduction to Machine Learning
---
## Carlos Ramirez-Perez
### Email: [cross224@hotmail.com](cross224@hotmail.com)
### Github: [carap/uea4502027](github.com/carap/uea4502027)

# Linear Algebra for Machine Learning

**Machine learning** (ML) is a branch of **Artificial Intelligence** (AI) that systematically applies **algorithms** to *synthesize* the underlying **functional relationships** among **data** and **information**

> ######  Breviary...
* This is a fancy way for referring to **inductive function approximation/description**
* We can formulate different ML problems as some form of **Optimization** 
    * labeling, summarizing, behavior
* At first, it seems that we do not need **Linear Algebra** for *getting started* with **Machine Learning**... but rapidly we will need to dive deeper.

# Linear Algebra for Machine Learning
If there is **one area of mathematics** suggested for improving before any other, it would be **Linear Algebra** 
* It will help us to *understand* and *get more out* of **ML algorithms** 
* It help us with other areas of mathematics, like **Statistics** and **Optimization**

# Linear Algebra for Machine Learning

Linear Algebra extremely facilitates **parallel computing**

ML is **data intensive**, representing large sets of data in **Matrix** form allows to take advantage of **batch processing** (*non-interactive batch jobs*)
* **Matrices** help us to look at all the data as a single abstract entity

Linear Algebra operations can be implemented without *message passing*
* it makes them appropriate to **MapReduce implementations** (*big data*)
* [MapReduce: simplified data processing on large clusters, ACM Communications Magazine, 2008](http://dl.acm.org/citation.cfm?id=1327492)


# What is Linear Algebra?
**Algebra** is the branch of mathematics that deals with *unknown values* being represented in the form of *variables*
* Roughly speaking, Linear Algebra is an **N-dimensional extension** of the same idea
* In Linear Algebra, data is represented in the form of **linear equations** 
* Linear equations are in turn represented in the form of **N-dimensional vectors** (matrices, hyperplanes).

# What is Linear Algebra?
As a branch of mathematics, it concisely describes **coordinate systems** (*vector spaces*), and the **interactions** and **operations** of *hyperplanes* in *higher dimensions*, as well as linear **mappings/transformations** between such hyperplanes
* *hyperplane* is a **subspace** of *one dimension less* than its environment space
* *vector space* is a collection of abstract objects called **vectors**, which may be added and multiplied (scaled) by numbers, called **scalars**.


# Properties of vector spaces
Properties of vector spaces |  Mathematical expressions of properties
:-|:-
Additive| $\mathbf{v},\mathbf{w} \in \mathbf{V} \implies \mathbf{v}+\mathbf{w} \in \mathbf{V}$
Commutative| $\mathbf{v}+\mathbf{w} = \mathbf{v}+\mathbf{w}$
Associative| $\mathbf{v}+(\mathbf{w}+\mathbf{z})= (\mathbf{v}+\mathbf{w})+\mathbf{z}$
Zero vector| $\mathbf{0}$
Identity | $\mathbf{0}+\mathbf{v} = \mathbf{v}+\mathbf{0} = \mathbf{0}$
Inverse | $\mathbf{v}+(-\mathbf{v}) = \mathbf{0}$
Scaling | $c\cdot\mathbf{v}=(cv_1,\dots,cv_n) , \quad c\in\mathbb{R} $

> Together, these properties describe a **commutative group under addition**

---
# Numpy for Linear Algebra
---

# Numpy for Linear Algebra
1. ndarray: The N-dimensional array
    * One-dimensional arrays
    * Two-dimensional arrays
    * Three or more dimensions
    * Array attributes and methods
2. Dot and cross products
3. Linear algebra functions

# Reminder...
## Numpy employs *four strategies* for speeding-up code
1. Use NumPy’s `ufuncs`
2. Use NumPy’s `aggregations` 
3. Use NumPy’s `broadcasting`
4. Use NumPy’s `slicing`, `masking`, and `fancy-indexing`

> ######  Overall goal: 
* Implement **repeated operations** into compiled code and get rid of **slow loops**!

---
# Numpy usage
---

In [1]:
import numpy as np

# N-dimensional array: `ndarray()`
Use the `np.ndarray` constructor to create an array with any number of dimensions. 
> `np.ndarray(shape, dtype, buffer,...)`  

# One-dimensional arrays
Creating a vector of float values

In [2]:
v = np.ndarray(shape=(1,4), 
               dtype=np.float16,
               buffer=np.array([2.4, -1.5, 3.0, 8.8]))
v

array([[ 0.22497559,  0.22497559,  0.22497559,  2.00585938]], dtype=float16)

In [3]:
v = np.ndarray((1,4), np.float16, np.array([2.4, -1.5, 3.0, 8.8]))
v

array([[ 0.22497559,  0.22497559,  0.22497559,  2.00585938]], dtype=float16)

> `np.array` is a *interface function* to create an `np.ndarray` 
* Arrays should be constructed using `np.array`, `np.zeros`, etc.

# One-dimensional arrays
Creating a vector of float values

In [4]:
v = np.array([2.4, -1.5, 3.0, 8.8], dtype=np.float16)
w = np.array([2.4, -1.5, 3.0, 8.8], dtype=np.float128)

In [5]:

[type(v), v.size], [type(w), w.size]  # attribute 'size'

([numpy.ndarray, 4], [numpy.ndarray, 4])

In [6]:
from sys import getsizeof  # Return the size of an object in bytes
help(getsizeof)

Help on built-in function getsizeof in module sys:

getsizeof(...)
    getsizeof(object, default) -> int
    
    Return the size of object in bytes.



In [7]:
[getsizeof(v),getsizeof(w)]

[104, 160]

---
# NumPy Indexing and Selection
---

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists

In [8]:
#Get the value at a specific index
v[0], w[0]

(2.4004, 2.3999999999999999112)

In [9]:
#Get a value at an index
[x for x in v] , [x for x in w] 

([2.4004, -1.5, 3.0, 8.7969],
 [2.3999999999999999112, -1.5, 3.0, 8.8000000000000007105])

# `arange()`: Arithmetic progression
Use the np.arange() function to build a vector containing an **arithmetic progression** (*adding common difference*)
> np.arange(start, stop=None, step=1, dtype=None) 

# Creating a sample array

In [10]:
arr = np.arange(0,11)  
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr[8]   # Bracket indexing to get values

8

In [12]:
arr[2:5]  # Get values in range [2,4]

array([2, 3, 4])

In [13]:
arr[:]   # Get values in all range (interval)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Broadcasting
Numpy `array` differs from normal Python `list` because of their ability to broadcast

In [14]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# Setting a value with index range (Broadcasting strategy)
arr[0:5]=100 
arr[:]

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

# Slicing and Broadcasting
Reset array

In [16]:
arr = np.arange(0,11) # reset
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr = arr[0:6]  # Slicing arr
slice_of_arr[:]          # Indexing every element (broadcast)

array([0, 1, 2, 3, 4, 5])

In [18]:
slice_of_arr[:] = 99   # Value broadcasted to slice
slice_of_arr[:]

array([99, 99, 99, 99, 99, 99])

In [19]:
arr[:]   # Changes also occur in our original array!

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Slicing and Broadcasting
With `slicing`, data is not copied, it's a view of the original array (cross-section alias). 
* To get a copy, we need to be explicit

In [20]:
arr_copy = arr.copy()   # Copy method
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing 2D arrays (matrices)
The general format is **`arr_2d[row][col]`** or **`arr_2d[row,col]`** 
* Recommended using the comma notation for clarity.


In [21]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d[:]  # Every row and column

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [22]:
arr_2d[1]   #Indexing row

array([20, 25, 30])

In [23]:
arr_2d[1][0]  # Getting individual element value

20

In [24]:
arr_2d[1,0]   # Getting individual element value

20

# Indexing 2D arrays (matrices)
General format is **`arr_2d[row][col]`** or **`arr_2d[row,col]`** 

In [25]:
arr_2d[:,:]  # Every row and column

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[0:3,0:3]  # Every row and column

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [27]:
arr_2d[0:,0:]  # Every row and column (since)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
arr_2d[:3,:3]  # # Every row and column (up to)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

# Slicing 2D arrays (matrices)
General format is **`arr_2d[row][col]`** or **`arr_2d[row,col]`** 

In [29]:
arr_2d[:,:]  # Every row and column

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr_2d[0:2,1:3]  # Shape (2,2) from top right corner

array([[10, 15],
       [25, 30]])

In [31]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# Slicing 2D arrays (matrices)
General format is **`arr_2d[row][col]`** or **`arr_2d[row,col]`** 

In [32]:
arr_2d[:,:]  # Every row and column

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [33]:
arr_2d[[0,1],:]  # Shape (2,2) from top right corner

array([[ 5, 10, 15],
       [20, 25, 30]])

In [34]:
arr_2d[[0,1],:][:,[1,2]]

array([[10, 15],
       [25, 30]])

 ---
 # Vector Operations
 ---

 # Dot and cross products

In [35]:
v1 = np.array([[1, 2, -4], [3, -1, 5]])
v1[:]

array([[ 1,  2, -4],
       [ 3, -1,  5]])

In [36]:
v2 = np.array([[6, -3], [1, -2], [2, 4]])
v2[:]

array([[ 6, -3],
       [ 1, -2],
       [ 2,  4]])

In [37]:
np.dot(v1, v2)

array([[  0, -23],
       [ 27,  13]])

# That's it for now!... Thanks.